export type CssTargetKind = "token" | "ui" | "editor-ui";

export interface CssTarget {
  readonly path: string;
  readonly kind: CssTargetKind;
  readonly firstLine: string;
  readonly sourceModules: readonly string[];
  readonly migrated: boolean;
}

export const CSS_TARGETS: readonly CssTarget[] = [
  { path: "Tokens/colors.css", kind: "token", firstLine: "/* Adlaire-Design color tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/typography.css", kind: "token", firstLine: "/* Adlaire-Design typography tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/spacing.css", kind: "token", firstLine: "/* Adlaire-Design spacing tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/layout.css", kind: "token", firstLine: "/* Adlaire-Design layout tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/motion.css", kind: "token", firstLine: "/* Adlaire-Design motion tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/layer.css", kind: "token", firstLine: "/* Adlaire-Design layer tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/breakpoints.css", kind: "token", firstLine: "/* Adlaire-Design breakpoint tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/surface.css", kind: "token", firstLine: "/* Adlaire-Design surface tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/status.css", kind: "token", firstLine: "/* Adlaire-Design status tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "Tokens/effects.css", kind: "token", firstLine: "/* Adlaire-Design effect tokens */", sourceModules: ["tokens.ts"], migrated: true },
  { path: "UI/adlaire.css", kind: "ui", firstLine: "/* Adlaire-Design color utilities */", sourceModules: ["rules.ts", "rules-adlaire.ts"], migrated: true },
  { path: "UI/base.css", kind: "ui", firstLine: "/* Adlaire-Design base styles */", sourceModules: ["rules.ts", "rules-base.ts"], migrated: true },
  { path: "UI/grid.css", kind: "ui", firstLine: "/* Adlaire-Design grid utilities */", sourceModules: ["rules.ts", "rules-grid.ts"], migrated: true },
  { path: "UI/layout.css", kind: "ui", firstLine: "/* Adlaire-Design public layout */", sourceModules: ["rules.ts", "rules-layout.ts"], migrated: true },
  { path: "UI/components.css", kind: "ui", firstLine: "/* Adlaire-Design public components */", sourceModules: ["rules.ts", "rules-components.ts", "rules-components-foundation.ts", "rules-components-foundation-core.ts", "rules-components-foundation-core-base.ts", "rules-components-foundation-core-controls.ts", "rules-components-foundation-core-status.ts", "rules-components-foundation-core-data.ts", "rules-components-foundation-core-announcements.ts", "rules-components-foundation-core-flow.ts", "rules-components-foundation-core-media.ts", "rules-components-foundation-media.ts", "rules-components-foundation-media-base.ts", "rules-components-foundation-media-cards.ts", "rules-components-foundation-media-governance.ts", "rules-components-foundation-media-operations.ts", "rules-components-foundation-media-app.ts", "rules-components-foundation-domains.ts", "rules-components-foundation-domains-product.ts", "rules-components-foundation-domains-commerce.ts", "rules-components-foundation-domains-data.ts", "rules-components-foundation-domains-collaboration.ts", "rules-components-foundation-domains-workflow.ts", "rules-components-foundation-domains-observability.ts", "rules-components-foundation-support.ts", "rules-components-foundation-support-cards.ts", "rules-components-foundation-support-panels.ts", "rules-components-foundation-support-layout.ts", "rules-components-foundation-support-pagination.ts", "rules-components-foundation-support-filters.ts", "rules-components-overlays.ts", "rules-components-overlays-surfaces.ts", "rules-components-overlays-carousel.ts", "rules-components-overlays-tooltip.ts", "rules-components-overlays-responsive.ts", "rules-components-overlays-catalog.ts", "rules-components-operations.ts", "rules-components-operations-admin.ts", "rules-components-operations-admin-layout.ts", "rules-components-operations-admin-states.ts", "rules-components-operations-admin-actions.ts", "rules-components-operations-admin-governance.ts", "rules-components-operations-admin-delivery.ts", "rules-components-operations-admin-lifecycle.ts", "rules-components-operations-admin-observability.ts", "rules-components-operations-admin-security.ts", "rules-components-operations-data.ts", "rules-components-operations-data-navigation.ts", "rules-components-operations-data-dialogs.ts", "rules-components-operations-data-search.ts", "rules-components-operations-data-tree.ts", "rules-components-operations-data-grid.ts", "rules-components-operations-data-inspection.ts", "rules-components-operations-data-bottom-sheet.ts", "rules-components-operations-workspace.ts", "rules-components-operations-workspace-tabs.ts", "rules-components-operations-workspace-menus.ts", "rules-components-operations-workspace-boards.ts", "rules-components-operations-workspace-metrics.ts", "rules-components-operations-workspace-assets.ts", "rules-components-operations-workspace-publishing.ts", "rules-components-operations-business.ts", "rules-components-operations-business-planning.ts", "rules-components-operations-business-enterprise.ts", "rules-components-operations-business-governance.ts", "rules-components-operations-business-industry.ts", "rules-components-operations-business-insights.ts", "rules-components-operations-business-messaging.ts", "rules-components-operations-industry.ts", "rules-components-operations-industry-content.ts", "rules-components-operations-industry-devices.ts", "rules-components-operations-industry-hospitality.ts", "rules-components-operations-industry-civic.ts", "rules-components-operations-industry-utilities.ts", "rules-components-operations-workflow.ts", "rules-components-operations-workflow-layout.ts", "rules-components-operations-workflow-records.ts", "rules-components-operations-workflow-automation.ts", "rules-components-platform.ts", "rules-components-platform-developer.ts", "rules-components-platform-theme.ts", "rules-components-platform-states.ts", "rules-components-platform-github.ts", "rules-components-platform-cloud.ts", "rules-components-platform-surfaces.ts"], migrated: true },
  { path: "UI/site.css", kind: "ui", firstLine: "/* Adlaire-Design site chrome */", sourceModules: ["rules.ts", "rules-site.ts"], migrated: true },
  { path: "UI/forms.css", kind: "ui", firstLine: "/* Adlaire-Design form components */", sourceModules: ["rules.ts", "rules-forms.ts", "rules-forms-foundation.ts", "rules-forms-foundation-base.ts", "rules-forms-foundation-controls.ts", "rules-forms-foundation-checks.ts", "rules-forms-foundation-buttons.ts", "rules-forms-foundation-notices.ts", "rules-forms-foundation-submit.ts", "rules-forms-composite.ts", "rules-forms-composite-filters.ts", "rules-forms-composite-input-groups.ts", "rules-forms-composite-date-time.ts", "rules-forms-composite-selects.ts", "rules-forms-composite-tokens.ts", "rules-forms-composite-calendar.ts", "rules-forms-upload.ts", "rules-forms-upload-files.ts", "rules-forms-upload-settings.ts", "rules-forms-upload-toggles.ts", "rules-forms-upload-danger.ts", "rules-forms-validation.ts", "rules-forms-validation-fields.ts", "rules-forms-validation-admin.ts", "rules-forms-validation-stepper.ts", "rules-forms-validation-builder.ts", "rules-forms-validation-responsive.ts", "rules-forms-validation-aliases.ts"], migrated: true },
  { path: "UI/content.css", kind: "ui", firstLine: "/* Adlaire-Design content components */", sourceModules: ["rules.ts", "rules-content.ts", "rules-content-foundation.ts", "rules-content-foundation-base.ts", "rules-content-foundation-patterns.ts", "rules-content-foundation-organization.ts", "rules-content-foundation-timeline.ts", "rules-content-foundation-tabs.ts", "rules-content-foundation-news.ts", "rules-content-extended.ts", "rules-content-extended-toc.ts", "rules-content-extended-knowledge.ts", "rules-content-extended-repository.ts", "rules-content-extended-markdown.ts", "rules-content-extended-activity.ts", "rules-content-extended-responsive.ts", "rules-content-catalog.ts", "rules-content-catalog-aliases.ts", "rules-content-catalog-news.ts", "rules-content-catalog-sidebar.ts", "rules-content-catalog-contact.ts", "rules-content-catalog-legal.ts", "rules-content-catalog-alerts.ts", "rules-content-interactions.ts", "rules-content-interactions-sorting.ts", "rules-content-interactions-desktop.ts", "rules-content-interactions-tablet.ts", "rules-content-interactions-mobile.ts"], migrated: true },
  { path: "UI/utilities.css", kind: "ui", firstLine: "/* Adlaire-Design utility classes */", sourceModules: ["rules.ts", "rules-utilities.ts"], migrated: true },
  { path: "UI/compat-agws.css", kind: "ui", firstLine: "/* Adlaire-Design specification layer */", sourceModules: ["rules.ts", "rules-compat-agws.ts"], migrated: true },
  { path: "EditorUI/wysiwyg.css", kind: "editor-ui", firstLine: "/* Adlaire-Design WYSIWYG editor */", sourceModules: ["rules.ts", "rules-wysiwyg.ts", "rules-wysiwyg-shell.ts", "rules-wysiwyg-shell-frame.ts", "rules-wysiwyg-shell-header.ts", "rules-wysiwyg-toolbar.ts", "rules-wysiwyg-toolbar-layout.ts", "rules-wysiwyg-toolbar-tools.ts", "rules-wysiwyg-toolbar-focus.ts", "rules-wysiwyg-toolbar-disabled.ts", "rules-wysiwyg-blocks.ts", "rules-wysiwyg-blocks-core.ts", "rules-wysiwyg-blocks-menus.ts", "rules-wysiwyg-blocks-preview.ts", "rules-wysiwyg-blocks-types.ts", "rules-wysiwyg-blocks-states.ts", "rules-wysiwyg-blocks-mobile.ts", "rules-wysiwyg-support.ts", "rules-wysiwyg-support-editing.ts", "rules-wysiwyg-support-panels.ts", "rules-wysiwyg-support-advanced.ts", "rules-wysiwyg-support-motion.ts", "rules-wysiwyg-support-tablet.ts", "rules-wysiwyg-support-mobile.ts", "rules-wysiwyg-extensions.ts", "rules-wysiwyg-extensions-panels.ts", "rules-wysiwyg-extensions-drag.ts", "rules-wysiwyg-extensions-feedback.ts", "rules-wysiwyg-extensions-blocks.ts", "rules-wysiwyg-extensions-states.ts", "rules-wysiwyg-extensions-collaboration.ts", "rules-wysiwyg-extensions-banners.ts"], migrated: true },
] as const;

export const FORBIDDEN_CSS_COMPILER_PATHS: readonly string[] = [
  "TypeScript/CSS/components/",
  "TypeScript/CSS/tokens/",
  "TypeScript/CSS/themes/",
  "TypeScript/CSS/plugins/",
  "TypeScript/CSS/adapters/",
] as const;

export const CSS_COMPILER_REQUIRED_FILES: readonly string[] = [
  "TypeScript/CSS/tokens.ts",
  "TypeScript/CSS/rules.ts",
  "TypeScript/CSS/rules-types.ts",
  "TypeScript/CSS/rules-adlaire.ts",
  "TypeScript/CSS/rules-base.ts",
  "TypeScript/CSS/rules-grid.ts",
  "TypeScript/CSS/rules-layout.ts",
  "TypeScript/CSS/rules-components.ts",
  "TypeScript/CSS/rules-components-foundation.ts",
  "TypeScript/CSS/rules-components-foundation-core.ts",
  "TypeScript/CSS/rules-components-foundation-core-base.ts",
  "TypeScript/CSS/rules-components-foundation-core-controls.ts",
  "TypeScript/CSS/rules-components-foundation-core-status.ts",
  "TypeScript/CSS/rules-components-foundation-core-data.ts",
  "TypeScript/CSS/rules-components-foundation-core-announcements.ts",
  "TypeScript/CSS/rules-components-foundation-core-flow.ts",
  "TypeScript/CSS/rules-components-foundation-core-media.ts",
  "TypeScript/CSS/rules-components-foundation-media.ts",
  "TypeScript/CSS/rules-components-foundation-media-base.ts",
  "TypeScript/CSS/rules-components-foundation-media-cards.ts",
  "TypeScript/CSS/rules-components-foundation-media-governance.ts",
  "TypeScript/CSS/rules-components-foundation-media-operations.ts",
  "TypeScript/CSS/rules-components-foundation-media-app.ts",
  "TypeScript/CSS/rules-components-foundation-domains.ts",
  "TypeScript/CSS/rules-components-foundation-domains-product.ts",
  "TypeScript/CSS/rules-components-foundation-domains-commerce.ts",
  "TypeScript/CSS/rules-components-foundation-domains-data.ts",
  "TypeScript/CSS/rules-components-foundation-domains-collaboration.ts",
  "TypeScript/CSS/rules-components-foundation-domains-workflow.ts",
  "TypeScript/CSS/rules-components-foundation-domains-observability.ts",
  "TypeScript/CSS/rules-components-foundation-support.ts",
  "TypeScript/CSS/rules-components-foundation-support-cards.ts",
  "TypeScript/CSS/rules-components-foundation-support-panels.ts",
  "TypeScript/CSS/rules-components-foundation-support-layout.ts",
  "TypeScript/CSS/rules-components-foundation-support-pagination.ts",
  "TypeScript/CSS/rules-components-foundation-support-filters.ts",
  "TypeScript/CSS/rules-components-overlays.ts",
  "TypeScript/CSS/rules-components-overlays-surfaces.ts",
  "TypeScript/CSS/rules-components-overlays-carousel.ts",
  "TypeScript/CSS/rules-components-overlays-tooltip.ts",
  "TypeScript/CSS/rules-components-overlays-responsive.ts",
  "TypeScript/CSS/rules-components-overlays-catalog.ts",
  "TypeScript/CSS/rules-components-operations.ts",
  "TypeScript/CSS/rules-components-operations-admin.ts",
  "TypeScript/CSS/rules-components-operations-admin-layout.ts",
  "TypeScript/CSS/rules-components-operations-admin-states.ts",
  "TypeScript/CSS/rules-components-operations-admin-actions.ts",
  "TypeScript/CSS/rules-components-operations-admin-governance.ts",
  "TypeScript/CSS/rules-components-operations-admin-delivery.ts",
  "TypeScript/CSS/rules-components-operations-admin-lifecycle.ts",
  "TypeScript/CSS/rules-components-operations-admin-observability.ts",
  "TypeScript/CSS/rules-components-operations-admin-security.ts",
  "TypeScript/CSS/rules-components-operations-data.ts",
  "TypeScript/CSS/rules-components-operations-data-navigation.ts",
  "TypeScript/CSS/rules-components-operations-data-dialogs.ts",
  "TypeScript/CSS/rules-components-operations-data-search.ts",
  "TypeScript/CSS/rules-components-operations-data-tree.ts",
  "TypeScript/CSS/rules-components-operations-data-grid.ts",
  "TypeScript/CSS/rules-components-operations-data-inspection.ts",
  "TypeScript/CSS/rules-components-operations-data-bottom-sheet.ts",
  "TypeScript/CSS/rules-components-operations-workspace.ts",
  "TypeScript/CSS/rules-components-operations-workspace-tabs.ts",
  "TypeScript/CSS/rules-components-operations-workspace-menus.ts",
  "TypeScript/CSS/rules-components-operations-workspace-boards.ts",
  "TypeScript/CSS/rules-components-operations-workspace-metrics.ts",
  "TypeScript/CSS/rules-components-operations-workspace-assets.ts",
  "TypeScript/CSS/rules-components-operations-workspace-publishing.ts",
  "TypeScript/CSS/rules-components-operations-business.ts",
  "TypeScript/CSS/rules-components-operations-business-planning.ts",
  "TypeScript/CSS/rules-components-operations-business-enterprise.ts",
  "TypeScript/CSS/rules-components-operations-business-governance.ts",
  "TypeScript/CSS/rules-components-operations-business-industry.ts",
  "TypeScript/CSS/rules-components-operations-business-insights.ts",
  "TypeScript/CSS/rules-components-operations-business-messaging.ts",
  "TypeScript/CSS/rules-components-operations-industry.ts",
  "TypeScript/CSS/rules-components-operations-industry-content.ts",
  "TypeScript/CSS/rules-components-operations-industry-devices.ts",
  "TypeScript/CSS/rules-components-operations-industry-hospitality.ts",
  "TypeScript/CSS/rules-components-operations-industry-civic.ts",
  "TypeScript/CSS/rules-components-operations-industry-utilities.ts",
  "TypeScript/CSS/rules-components-operations-workflow.ts",
  "TypeScript/CSS/rules-components-operations-workflow-layout.ts",
  "TypeScript/CSS/rules-components-operations-workflow-records.ts",
  "TypeScript/CSS/rules-components-operations-workflow-automation.ts",
  "TypeScript/CSS/rules-components-platform.ts",
  "TypeScript/CSS/rules-components-platform-developer.ts",
  "TypeScript/CSS/rules-components-platform-theme.ts",
  "TypeScript/CSS/rules-components-platform-states.ts",
  "TypeScript/CSS/rules-components-platform-github.ts",
  "TypeScript/CSS/rules-components-platform-cloud.ts",
  "TypeScript/CSS/rules-components-platform-surfaces.ts",
  "TypeScript/CSS/rules-site.ts",
  "TypeScript/CSS/rules-forms.ts",
  "TypeScript/CSS/rules-forms-foundation.ts",
  "TypeScript/CSS/rules-forms-foundation-base.ts",
  "TypeScript/CSS/rules-forms-foundation-controls.ts",
  "TypeScript/CSS/rules-forms-foundation-checks.ts",
  "TypeScript/CSS/rules-forms-foundation-buttons.ts",
  "TypeScript/CSS/rules-forms-foundation-notices.ts",
  "TypeScript/CSS/rules-forms-foundation-submit.ts",
  "TypeScript/CSS/rules-forms-composite.ts",
  "TypeScript/CSS/rules-forms-composite-filters.ts",
  "TypeScript/CSS/rules-forms-composite-input-groups.ts",
  "TypeScript/CSS/rules-forms-composite-date-time.ts",
  "TypeScript/CSS/rules-forms-composite-selects.ts",
  "TypeScript/CSS/rules-forms-composite-tokens.ts",
  "TypeScript/CSS/rules-forms-composite-calendar.ts",
  "TypeScript/CSS/rules-forms-upload.ts",
  "TypeScript/CSS/rules-forms-upload-files.ts",
  "TypeScript/CSS/rules-forms-upload-settings.ts",
  "TypeScript/CSS/rules-forms-upload-toggles.ts",
  "TypeScript/CSS/rules-forms-upload-danger.ts",
  "TypeScript/CSS/rules-forms-validation.ts",
  "TypeScript/CSS/rules-forms-validation-fields.ts",
  "TypeScript/CSS/rules-forms-validation-admin.ts",
  "TypeScript/CSS/rules-forms-validation-stepper.ts",
  "TypeScript/CSS/rules-forms-validation-builder.ts",
  "TypeScript/CSS/rules-forms-validation-responsive.ts",
  "TypeScript/CSS/rules-forms-validation-aliases.ts",
  "TypeScript/CSS/rules-content.ts",
  "TypeScript/CSS/rules-content-foundation.ts",
  "TypeScript/CSS/rules-content-foundation-base.ts",
  "TypeScript/CSS/rules-content-foundation-patterns.ts",
  "TypeScript/CSS/rules-content-foundation-organization.ts",
  "TypeScript/CSS/rules-content-foundation-timeline.ts",
  "TypeScript/CSS/rules-content-foundation-tabs.ts",
  "TypeScript/CSS/rules-content-foundation-news.ts",
  "TypeScript/CSS/rules-content-extended.ts",
  "TypeScript/CSS/rules-content-extended-toc.ts",
  "TypeScript/CSS/rules-content-extended-knowledge.ts",
  "TypeScript/CSS/rules-content-extended-repository.ts",
  "TypeScript/CSS/rules-content-extended-markdown.ts",
  "TypeScript/CSS/rules-content-extended-activity.ts",
  "TypeScript/CSS/rules-content-extended-responsive.ts",
  "TypeScript/CSS/rules-content-catalog.ts",
  "TypeScript/CSS/rules-content-catalog-aliases.ts",
  "TypeScript/CSS/rules-content-catalog-news.ts",
  "TypeScript/CSS/rules-content-catalog-sidebar.ts",
  "TypeScript/CSS/rules-content-catalog-contact.ts",
  "TypeScript/CSS/rules-content-catalog-legal.ts",
  "TypeScript/CSS/rules-content-catalog-alerts.ts",
  "TypeScript/CSS/rules-content-interactions.ts",
  "TypeScript/CSS/rules-content-interactions-sorting.ts",
  "TypeScript/CSS/rules-content-interactions-desktop.ts",
  "TypeScript/CSS/rules-content-interactions-tablet.ts",
  "TypeScript/CSS/rules-content-interactions-mobile.ts",
  "TypeScript/CSS/rules-utilities.ts",
  "TypeScript/CSS/rules-compat-agws.ts",
  "TypeScript/CSS/rules-wysiwyg.ts",
  "TypeScript/CSS/rules-wysiwyg-shell.ts",
  "TypeScript/CSS/rules-wysiwyg-shell-frame.ts",
  "TypeScript/CSS/rules-wysiwyg-shell-header.ts",
  "TypeScript/CSS/rules-wysiwyg-toolbar.ts",
  "TypeScript/CSS/rules-wysiwyg-toolbar-layout.ts",
  "TypeScript/CSS/rules-wysiwyg-toolbar-tools.ts",
  "TypeScript/CSS/rules-wysiwyg-toolbar-focus.ts",
  "TypeScript/CSS/rules-wysiwyg-toolbar-disabled.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-core.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-menus.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-preview.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-types.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-states.ts",
  "TypeScript/CSS/rules-wysiwyg-blocks-mobile.ts",
  "TypeScript/CSS/rules-wysiwyg-support.ts",
  "TypeScript/CSS/rules-wysiwyg-support-editing.ts",
  "TypeScript/CSS/rules-wysiwyg-support-panels.ts",
  "TypeScript/CSS/rules-wysiwyg-support-advanced.ts",
  "TypeScript/CSS/rules-wysiwyg-support-motion.ts",
  "TypeScript/CSS/rules-wysiwyg-support-tablet.ts",
  "TypeScript/CSS/rules-wysiwyg-support-mobile.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-panels.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-drag.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-feedback.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-blocks.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-states.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-collaboration.ts",
  "TypeScript/CSS/rules-wysiwyg-extensions-banners.ts",
  "TypeScript/CSS/targets.ts",
  "TypeScript/CSS/emit.ts",
  "TypeScript/CSS/manifest.ts",
  "TypeScript/CSS/index.ts",
] as const;

export function cssTargetPaths(kind?: CssTargetKind): readonly string[] {
  return CSS_TARGETS
    .filter((target) => kind === undefined || target.kind === kind)
    .map((target) => target.path);
}

export function cssCompilerSourceModules(): readonly string[] {
  return Array.from(new Set(CSS_TARGETS.flatMap((target) => target.sourceModules.map((source) => `TypeScript/CSS/${source}`))));
}
